### ISSUE TITLE
Замечания @Alexeyzlat

### ISSUE THREAD

**Issue by ananasn** [Alexeyzlat/laboratornaya2#1]
* Обратите внимание на то, сколько пробельных строк должно быть между определениями функций по [PEP8](https://www.python.org/dev/peps/pep-0008/) и поправьте.
* Функции `check_genre`, `check_category`, `check_developer`, `check_platform` используют глобальные переменные, так делать не нужно (только при большой необходимости, но это не ваш случай). Вместо глобальных переменных используйте параметры.
* Фактически у вас повторяется код вида `any(genre in game_desc for genre in genres) or (genres == [''])` только меняется название genres. Из это всего нужно сделать одну универсальную функцию, которая принимает два параметра -- что искать и  в каком списке.

**Comment by Alexeyzlat** [comment]
Здравствуйте еще раз! Я обязательно поправлю. 
Я пропустил несколько тестов, сегодня на паре Вы сказали, что Вы можете открыть доступ, если ты не присутствовал на тесте. Можете открыть доступ для меня? 
Спасибо ☺️

**Comment by ananasn** [comment]
Открою доступ на пропущенные вами тесты 2-4 на завтра с 20-00 до 23-00

**Comment by Alexeyzlat** [comment]
Большое спасибо ☺️
